const MENU = {
  eat: ['奶油火鸡面','新疆炒米粉','火锅','烧烤','烤肉','海底捞','公瑾爆蛋','番茄滑肉','牛肉','辣椒炒肉','家庭厨房','原味鸡','麦当劳','塔斯汀','汉堡','韩式拌饭','粥','大碗先生','盛香亭','三文鱼','鸡胸肉','小龙虾','日料','滨寿司','大萝家泡菜','邵阳米粉','炸鸡腿','食货青年','烤鸭','馄饨'],
  drink: ['古茗','一点点','喜茶','库迪','新佳宜','可乐','果茶','啤酒','白酒','清酒','牛奶','草莓奶昔','草莓芭乐','鸡尾酒','咖啡','果汁'],
  fruit: ['荔枝','西瓜','榴莲','甜品','蛋糕']
};
const LABELS = { eat:'吃', drink:'喝', fruit:'水果', note:'备注' };
const STORAGE_KEY = 'baobao-menu-state-v1';
const state = { activeCategory:'eat', selected:{ eat:[], drink:[], fruit:[] }, note:'' };
const $ = (selector) => document.querySelector(selector);
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');state.activeCategory=['eat','drink','fruit','note'].includes(saved.activeCategory)?saved.activeCategory:'eat';for(const key of Object.keys(MENU))state.selected[key]=Array.isArray(saved.selected?.[key])?saved.selected[key].filter(item=>MENU[key].includes(item)):[];state.note=typeof saved.note==='string'?saved.note.slice(0,200):'';}catch(error){console.warn('无法恢复上次选择',error);}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({activeCategory:state.activeCategory,selected:state.selected,note:state.note}));}
function totalSelected(){return Object.values(state.selected).reduce((sum,items)=>sum+items.length,0);}
function renderTabs(){document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('is-active',tab.dataset.category===state.activeCategory));}
function renderProgress(){const total=totalSelected();$('#progressText').textContent=`已选择 ${total} 项`;$('#summaryCount').textContent=total?`已选择 ${total} 项`:'还没有选择';$('#categoryCount').textContent=state.activeCategory==='note'?(state.note?'✓':'0'):state.selected[state.activeCategory].length;}
function escapeHtml(value){return value.replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));}
function renderMenuCards(){const grid=$('#menuGrid');if(state.activeCategory==='note'){grid.hidden=true;return;}grid.hidden=false;const selected=state.selected[state.activeCategory];grid.innerHTML=MENU[state.activeCategory].map(item=>{const isSelected=selected.includes(item);return `<button type="button" class="menu-card${isSelected?' is-selected':''}" data-item="${escapeHtml(item)}" aria-pressed="${isSelected}"><span>${escapeHtml(item)}</span><span class="check-mark" aria-hidden="true">✓</span></button>`;}).join('');grid.querySelectorAll('.menu-card').forEach(card=>card.addEventListener('click',()=>toggleItem(card.dataset.item)));}
function renderNotePanel(){const visible=state.activeCategory==='note';$('#notePanel').hidden=!visible;$('#noteInput').value=state.note;$('#noteCount').textContent=`${state.note.length}/200`;}
function renderCategory(){const isNote=state.activeCategory==='note';$('#sectionKicker').textContent=isNote?'给宝宝的小纸条':state.activeCategory==='drink'?'宝宝想喝什么':`宝宝想${LABELS[state.activeCategory]}什么`;$('#sectionTitle').textContent=isNote?'有什么想对我说的？':'选一点喜欢的';renderMenuCards();renderNotePanel();renderProgress();}
function render(){renderTabs();renderCategory();}
function toggleItem(item){const selected=state.selected[state.activeCategory];const index=selected.indexOf(item);if(index===-1)selected.push(item);else selected.splice(index,1);saveState();render();}
function buildSummaryText(){const lines=['宝宝的点餐清单'];for(const key of ['eat','drink','fruit'])lines.push(`${LABELS[key]}：${state.selected[key].length?state.selected[key].join('、'):'暂未选择'}`);lines.push(`备注：${state.note.trim()||'无'}`);return lines.join('\n');}
function renderSummary(){$('#summaryContent').innerHTML=['eat','drink','fruit'].map(key=>`<section class="summary-group"><h3>${LABELS[key]}</h3><p class="${state.selected[key].length?'':'summary-empty'}">${escapeHtml(state.selected[key].length?state.selected[key].join('、'):'暂未选择')}</p></section>`).join('')+`<section class="summary-group"><h3>备注</h3><p class="${state.note.trim()?'':'summary-empty'}">${escapeHtml(state.note.trim()||'暂无备注')}</p></section>`;}
function setStatus(message){$('#actionStatus').textContent=message;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>{$('#actionStatus').textContent='';},2400);}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true;}catch(error){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();let ok=false;try{ok=document.execCommand('copy');}catch(e){}area.remove();return ok;}}
async function shareSummary(){const text=buildSummaryText();if(navigator.share){try{await navigator.share({title:'宝宝的点餐清单',text});setStatus('已打开分享面板');return;}catch(error){if(error.name==='AbortError')return;}}const ok=await copyText(text);setStatus(ok?'暂不支持直接分享，已复制清单':'分享失败，请长按清单复制');}
function clearAll(){if(!confirm('确定要清空所有选择吗？'))return;state.selected={eat:[],drink:[],fruit:[]};state.note='';saveState();render();$('#summaryDialog').close();}
document.addEventListener('DOMContentLoaded',()=>{loadState();document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{state.activeCategory=tab.dataset.category;saveState();render();}));$('#noteInput').addEventListener('input',event=>{state.note=event.target.value.slice(0,200);saveState();$('#noteCount').textContent=`${state.note.length}/200`;renderProgress();});$('#summaryButton').addEventListener('click',()=>{renderSummary();$('#summaryDialog').showModal();});$('#closeSummaryButton').addEventListener('click',()=>$('#summaryDialog').close());$('#copyButton').addEventListener('click',async()=>setStatus(await copyText(buildSummaryText())?'已复制到剪贴板':'复制失败，请长按清单复制'));$('#shareButton').addEventListener('click',shareSummary);$('#clearButton').addEventListener('click',clearAll);$('#summaryDialog').addEventListener('click',event=>{if(event.target===$('#summaryDialog'))$('#summaryDialog').close();});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});});
